#!name=流利说·阅读
#!desc=流利说·阅读
#!openUrl=https://t.me/Functional_Store_Hub
#!author=@R·E https://t.me/Functional_Store_Hub
#!manual=https://t.me/Functional_Store_Hub/10
#!icon=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/Files/icon.png
#!other=LiuLiShuoYueDu.Shadowrocket.model

[Script]
流利说·阅读=type=http-response,pattern=^https?:\/\/vira\.llsapp\.com\/api\/v\d\/\w+\/\w+$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/LiuLiShuoYueDu/Script/LiuLiShuoYueDu.js,script-update-interval=0

[MITM]
hostname = %APPEND% vira.llsapp.com
